version: "3"
services:
  server:
    image: kimsup10/palmtree
    command: java -jar -Dspring.profiles.active=dev -Dapp.shared=/home/deploy/palmtree ./target/palmtree-0.0.1-SNAPSHOT.jar
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - "./bin/db/:/docker-entrypoint-initdb.d/"
      - "./db-data:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "sooksook"
      MYSQL_USER: "sooksook"
      MYSQL_PASSWORD: "sooksook7890"
      MYSQL_ROOT_PASSWORD: "root"
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - "./proxy/nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - server