version: "3"
services:
  server:
    build: .
    ports:
      - "8080:8080"
  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - "./bin/db/:/docker-entrypoint-initdb.d/"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "sooksook"
      MYSQL_USER: "sooksook"
      MYSQL_PASSWORD: "sooksook7890"
      MYSQL_ROOT_PASSWORD: "root"
  adminer:
    image: adminer
    container_name: adminer
    ports:
    - 8080:8080